var Vue = require('vue')
var VueRouter = require('vue-router')

Vue.use(VueRouter)

export default new VueRouter({
  mode: 'history',
  scrollBehavior: () => ({y: 0}),
  routes: [
    { path: '*', component: resolve => require(['./components/err404'], resolve) },
    { path: '/',                redirect: '/login' },
    { path: '/error404',        component: resolve => require(['./components/err404'], resolve) },
    { path: '/error401',        component: resolve => require(['./components/err401'], resolve) },
    { path: '/error',           component: resolve => require(['./components/errpage'], resolve) },
    { path: '/login',           component: resolve => require(['./views/login'], resolve) },
    { path: '/loginNca',           component: resolve => require(['./views/loginNca'], resolve) },
    { path: '/loginErc',           component: resolve => require(['./views/loginErc'], resolve) },
    { path: '/ERCSaleOutInvoiceControl',     component: resolve => require(['./views/erc/inventorymanage/ERCSaleOutInvoiceControl'], resolve) },
    { path: '/ERCMaterialInvoiceControl',     component: resolve => require(['./views/erc/ordermanage/ERCOrderDetailControl/ERCMaterialInvoiceControl.vue'], resolve) },
    { path: '/common/baseconfig',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'FollowerControl',             component: resolve => require(['./views/common/baseconfig/FollowerControl'], resolve) }
    ]},
    { path: '/common/system',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'SystemApiControl',             component: resolve => require(['./views/common/system/SystemApiControl'], resolve) },
            { path: 'DomainTemplateControl',        component: resolve => require(['./views/common/system/DomainTemplateControl'], resolve) },
            { path: 'DomainControl',                component: resolve => require(['./views/common/system/DomainControl'], resolve) },
            { path: 'DomainGroupControl',           component: resolve => require(['./views/common/system/DomainGroupControl'], resolve) },
            { path: 'OperatorControl',              component: resolve => require(['./views/common/system/OperatorControl'], resolve) },
            { path: 'SysGroupApiControl',           component: resolve => require(['./views/common/system/SysGroupApiControl'], resolve) },
            { path: 'UserSetting',                  component: resolve => require(['./views/common/system/UserSetting'], resolve) },
            { path: 'ResetPassword',                component: resolve => require(['./views/common/system/ResetPassword'], resolve) }
    ]},
    { path: '/erc/customermanage',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'ERCCustomerControl',           component: resolve => require(['./views/erc/customermanage/ERCCustomerControl'], resolve) },
            { path: 'ERCCustomerDetailControl',     component: resolve => require(['./views/erc/customermanage/ERCCustomerDetailControl'], resolve) },
            { path: 'ERCAppointmentControl',        component: resolve => require(['./views/erc/customermanage/ERCAppointmentControl'], resolve) },
            { path: 'ERCInquiryControl',            component: resolve => require(['./views/erc/customermanage/ERCInquiryControl.vue'], resolve) },
            { path: 'ERCCustomerAssignControl',     component: resolve => require(['./views/erc/customermanage/ERCCustomerAssignControl.vue'], resolve) },
            { path: 'ERCCustomerAssignDetailControl',   component: resolve => require(['./views/erc/customermanage/ERCCustomerAssignDetailControl.vue'], resolve) },
            { path: 'ERCComplaintControl',              component: resolve => require(['./views/erc/customermanage/ERCComplaintControl'], resolve) },
            { path: 'ERCUserComplaintControl',              component: resolve => require(['./views/erc/customermanage/ERCUserComplaintControl'], resolve) },
            { path: 'ERCLoanControl',      component: resolve => require(['./views/erc/customermanage/ERCLoanControl'], resolve) }
        ]},
    { path: '/erc/ERCOrderSearchControl',     component: resolve => require(['./views/erc/ordermanage/ERCOrderSearchControl'], resolve) },
    { path: '/erc/ordermanage',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'ERCOrderControl',              component: resolve => require(['./views/erc/ordermanage/ERCOrderControl'], resolve) },
            { path: 'ERCLandAgentOrderControl',     component: resolve => require(['./views/erc/ordermanage/ERCLandAgentOrderControl'], resolve) },
            { path: 'ERCOrderDetailControl',        component: resolve => require(['./views/erc/ordermanage/ERCOrderDetailControl/ERCOrderDetailControl.vue'], resolve) },
            { path: 'ERCGOrderDetailControl',       component: resolve => require(['./views/erc/ordermanage/ERCGOrderDetailControl/ERCGOrderDetailControl.vue'], resolve) },
            { path: 'ERCOrderRequireControl',       component: resolve => require(['./views/erc/ordermanage/ERCOrderRequireControl.vue'], resolve) },
            { path: 'ERCMaterialInvoiceControl',    component: resolve => require(['./views/erc/ordermanage/ERCOrderDetailControl/ERCMaterialInvoiceControl.vue'], resolve) },
            { path: 'ERCSOrderDetailControl',       component: resolve => require(['./views/erc/ordermanage/ERCSOrderDetailControl/ERCSOrderDetailControl.vue'], resolve) },
            { path: 'ERCHDOrderControl',            component: resolve => require(['./views/erc/ordermanage/ERCHDOrderControl/ERCHDOrderControl.vue'], resolve) },
            { path: 'ERCHDOrderDetailControl',      component: resolve => require(['./views/erc/ordermanage/ERCHDOrderControl/ERCHDOrderDetailControl.vue'], resolve) },
            { path: 'ERCReceivablesRuleControl',    component: resolve => require(['./views/erc/ordermanage/ERCReceivablesRuleControl.vue'], resolve) },
            { path: 'ERCSaleOrderInstitutionsControl',    component: resolve => require(['./views/erc/ordermanage/ERCSaleOrderInstitutionsControl'], resolve) },
            { path: 'ERCSaleOrderControl',    component: resolve => require(['./views/erc/ordermanage/ERCSaleOrderControl'], resolve) },
            { path: 'ERCSaleOrderCompanyControl',    component: resolve => require(['./views/erc/ordermanage/ERCSaleOrderCompanyControl'], resolve) },
            { path: 'ERCOrderReviewControl',    component: resolve => require(['./views/erc/ordermanage/ERCOrderReviewControl.vue'], resolve) },
            { path: 'ERCOrderReviewDetailControl',    component: resolve => require(['./views/erc/ordermanage/ERCOrderReviewDetailControl.vue'], resolve) },
            { path: 'ERCDeliveryDetailControl',    component: resolve => require(['./views/erc/ordermanage/ERCDeliveryDetailControl.vue'], resolve) }
    ]},
    { path: '/erc/baseconfig',        component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'ERCEstateControl',            component: resolve => require(['./views/erc/baseconfig/ERCEstateControl'], resolve) },
            { path: 'ERCLandAgentEstateControl',   component: resolve => require(['./views/erc/baseconfig/ERCLandAgentEstateControl'], resolve) },
            { path: 'ERCEstateDetailControl',      component: resolve => require(['./views/erc/baseconfig/ERCEstateDetailControl/ERCEstateDetailControl.vue'], resolve) },
            { path: 'ERCRoomTypeDetailControl',    component: resolve => require(['./views/erc/baseconfig/ERCRoomTypeDetailControl/ERCRoomTypeDetailControl.vue'], resolve) },
            { path: 'ERCMaterielControl',          component: resolve => require(['./views/erc/baseconfig/ERCMaterielControl'], resolve) },
            { path: 'ERCSupplierControl',          component: resolve => require(['./views/erc/baseconfig/ERCSupplierControl'], resolve) },
            { path: 'ERCSupplierTeamControl',      component: resolve => require(['./views/erc/baseconfig/ERCSupplierTeamControl'], resolve) },
            { path: 'ERCSupplierMaterielControl',  component: resolve => require(['./views/erc/baseconfig/ERCSupplierMaterielControl'], resolve) },
            { path: 'ERCSupplierProduceControl',  component: resolve => require(['./views/erc/baseconfig/ERCSupplierProduceControl'], resolve) },
            { path: 'ERCLandAgentControl',         component: resolve => require(['./views/erc/baseconfig/ERCLandAgentControl'], resolve) },
            { path: 'ERCLandAgentTeamControl',     component: resolve => require(['./views/erc/baseconfig/ERCLandAgentTeamControl'], resolve) },
            { path: 'ERCForemanControl',           component: resolve => require(['./views/erc/baseconfig/ERCForemanControl'], resolve) },
            { path: 'ERCProduceControl',           component: resolve => require(['./views/erc/baseconfig/ERCProduceControl'], resolve) },
            { path: 'ERCProduceDetailControl',     component: resolve => require(['./views/erc/baseconfig/ERCProduceDetailControl'], resolve) },
            { path: 'ERCMaterielReviewDetailControl',          component: resolve => require(['./views/erc/baseconfig/ERCMaterielReviewDetailControl'], resolve) },
            { path: 'ERCMaterielSyncControl',          component: resolve => require(['./views/erc/baseconfig/ERCMaterielSyncControl'], resolve) },
            { path: 'ERCTaskListControl',               component: resolve => require(['./views/erc/baseconfig/ERCTaskListControl'], resolve) },
            { path: 'ERCTaskDetailControl',             component: resolve => require(['./views/erc/baseconfig/ERCTaskDetailControl'], resolve) },
            { path: 'ERCTaskAllotControl',             component: resolve => require(['./views/erc/baseconfig/ERCTaskAllotControl'], resolve) },
            { path: 'ERCSiteConfigCaseControl',          component: resolve => require(['./views/erc/baseconfig/ERCSiteConfigCaseControl'], resolve) },
            { path: 'ERCSiteConfigDiaryControl',          component: resolve => require(['./views/erc/baseconfig/ERCSiteConfigDiaryControl'], resolve) },
            { path: 'ERCTaskAllotControl',             component: resolve => require(['./views/erc/baseconfig/ERCTaskAllotControl'], resolve) },
            { path: 'ERCWorkerControl',           component: resolve => require(['./views/erc/baseconfig/ERCWorkerControl'], resolve) },
            { path: 'ERCWorkerBranchControl',           component: resolve => require(['./views/erc/baseconfig/ERCWorkerBranchControl'], resolve) },
            { path: 'ERCProjectControl',           component: resolve => require(['./views/erc/baseconfig/ERCProjectControl'], resolve) },
            { path: 'ERCProjectDetailControl',           component: resolve => require(['./views/erc/baseconfig/ERCProjectDetailControl'], resolve) },
            { path: 'ERCProjectDetailNewControl',           component: resolve => require(['./views/erc/baseconfig/ERCProjectDetailNewControl'], resolve) },
            { path: 'ERCProjectSpaceDetailControl',           component: resolve => require(['./views/erc/baseconfig/ERCProjectSpaceDetailControl'], resolve) },
            { path: 'ERCFinalAccountControl',           component: resolve => require(['./views/erc/baseconfig/ERCFinalAccountControl'], resolve) },
            { path: 'ERCFinalAccountDetailControl',           component: resolve => require(['./views/erc/baseconfig/ERCFinalAccountDetailControl'], resolve) },
            { path: 'ERCFinalAccountSpaceControl',           component: resolve => require(['./views/erc/baseconfig/ERCFinalAccountSpaceControl'], resolve) },
            { path: 'ERCWorkerPriceControl',           component: resolve => require(['./views/erc/baseconfig/ERCWorkerPriceControl'], resolve) },
            { path: 'ERCNoticeControl',   component: resolve => require(['./views/erc/baseconfig/ERCNoticeControl'], resolve) },
            { path: 'ERCNoticeListControl',          component: resolve => require(['./views/erc/baseconfig/ERCNoticeListControl'], resolve) },
            { path: 'ERCNoticeDetailControl',          component: resolve => require(['./views/erc/baseconfig/ERCNoticeDetailControl'], resolve) },
            { path: 'ERCNoticeReceiveDetailControl',          component: resolve => require(['./views/erc/baseconfig/ERCNoticeReceiveDetailControl'], resolve) },
            { path: 'ERCHumanResourceControl',   component: resolve => require(['./views/erc/baseconfig/ERCHumanResourceControl'], resolve) },
            { path: 'ERCHumanResourceDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCHumanResourceDetailControl'], resolve) },
            { path: 'ERCAffiliatedCompanyControl',   component: resolve => require(['./views/erc/baseconfig/ERCAffiliatedCompanyControl'], resolve) },
            { path: 'ERCBusinessCustomerControl',   component: resolve => require(['./views/erc/baseconfig/ERCBusinessCustomerControl'], resolve) },
            { path: 'ERCBusinessCustomerDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCBusinessCustomerDetailControl'], resolve) },
            { path: 'ERCEmployeeInformationControl',   component: resolve => require(['./views/erc/baseconfig/ERCEmployeeInformationControl'], resolve) },
            { path: 'ERCEmployeeDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCEmployeeDetailControl'], resolve) },
            { path: 'ERCSmallProgramControl',   component: resolve => require(['./views/erc/baseconfig/ERCSmallProgramControl'], resolve) },
            { path: 'ERCReimburseRankControl',   component: resolve => require(['./views/erc/baseconfig/ERCReimburseRankControl'], resolve) },
            { path: 'ERCBaseDataControl',   component: resolve => require(['./views/erc/baseconfig/ERCBaseDataControl'], resolve) },
            { path: 'ERCMeetingManageControl',   component: resolve => require(['./views/erc/baseconfig/ERCMeetingManageControl'], resolve) },
            { path: 'ERCMeetingManageDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCMeetingManageDetailControl'], resolve) },
            { path: 'ERCMeetingRoomControl',   component: resolve => require(['./views/erc/baseconfig/ERCMeetingRoomControl'], resolve) },
            { path: 'ERCMeetingRoomDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCMeetingRoomDetailControl'], resolve) },
            { path: 'ERCMeetingMinuteControl',   component: resolve => require(['./views/erc/baseconfig/ERCMeetingMinuteControl'], resolve) },
            { path: 'ERCMeetingMinuteDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCMeetingMinuteDetailControl'], resolve) },
            { path: 'ERCVehicleControl',   component: resolve => require(['./views/erc/baseconfig/ERCVehicleControl'], resolve) },
            { path: 'ERCTransReceptionListControl',   component: resolve => require(['./views/erc/baseconfig/ERCTransReceptionListControl'], resolve) },
            { path: 'ERCTransReceptionDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCTransReceptionDetailControl'], resolve) },
            { path: 'ERCTransReceptionListExpenseControl',   component: resolve => require(['./views/erc/baseconfig/ERCTransReceptionListExpenseControl'], resolve) },
            { path: 'ERCAskForLeaveControl',   component: resolve => require(['./views/erc/baseconfig/ERCAskForLeaveControl'], resolve) },
            { path: 'ERCAskForLeaveDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCAskForLeaveDetailControl'], resolve) },
            { path: 'ERCAskForLeaveTaskDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCAskForLeaveTaskDetailControl'], resolve) },
            { path: 'ERCTransReceptionExpenseDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCTransReceptionExpenseDetailControl'], resolve) },
            { path: 'ERCDocumentManagementControl',   component: resolve => require(['./views/erc/baseconfig/ERCDocumentManagementControl'], resolve) },
            { path: 'ERCDocumentManagementDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCDocumentManagementDetailControl'], resolve) },
            { path: 'ERCTestInDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCTestInDetailControl'], resolve) },
            { path: 'ERCTestOutDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCTestOutDetailControl'], resolve) },
            { path: 'ERCDocumentManagementTaskDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCDocumentManagementTaskDetailControl'], resolve) },
            { path: 'ERCDocumentNoticeControl',   component: resolve => require(['./views/erc/baseconfig/ERCDocumentNoticeControl'], resolve) },
            { path: 'ERCDocumentNoticeDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCDocumentNoticeDetailControl'], resolve) },
            { path: 'ERCTestNoticeControl',   component: resolve => require(['./views/erc/baseconfig/ERCTestNoticeControl'], resolve) },
            { path: 'ERCTestOutNoticeControl',   component: resolve => require(['./views/erc/baseconfig/ERCTestOutNoticeControl'], resolve) },
            { path: 'ERCTestTaskInDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCTestTaskInDetailControl'], resolve) },
            { path: 'ERCTestTaskOutDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCTestTaskOutDetailControl'], resolve) },
            { path: 'ERCSpecialExpenseControl',   component: resolve => require(['./views/erc/baseconfig/ERCSpecialExpenseControl'], resolve) },
            { path: 'ERCTransReceptionDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCTransReceptionDetailControl'], resolve) },
            { path: 'ERCContentManageControl',   component: resolve => require(['./views/erc/baseconfig/ERCContentManageControl'], resolve) },
            { path: 'ERCContentManageDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCContentManageDetailControl'], resolve) },
            { path: 'ERCContentManageTypeControl',   component: resolve => require(['./views/erc/baseconfig/ERCContentManageTypeControl'], resolve) },
            { path: 'ERCCorporateClientsControl',   component: resolve => require(['./views/erc/baseconfig/ERCCorporateClientsControl'], resolve) },
            { path: 'ERCCorporateClientsDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCCorporateClientsDetailControl'], resolve) },
            { path: 'ERCDepartmentControl',   component: resolve => require(['./views/erc/baseconfig/ERCDepartmentControl'], resolve) },
            { path: 'ERCUsergroupControl',   component: resolve => require(['./views/erc/baseconfig/ERCUsergroupControl'], resolve) },
            { path: 'ERCCreditLineDetailtControl',   component: resolve => require(['./views/erc/baseconfig/ERCCreditLineDetailtControl'], resolve) },
            { path: 'ERCTestTaskAnswerInDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCTestTaskAnswerInDetailControl'], resolve) },
            { path: 'ERCDocumentManagementNoticeTaskDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCDocumentManagementNoticeTaskDetailControl'], resolve) },
            { path: 'ERCProductSalesPriceControl',   component: resolve => require(['./views/erc/baseconfig/ERCProductSalesPriceControl'], resolve) },
            { path: 'ERCProductSalesPriceDetailControl',   component: resolve => require(['./views/erc/baseconfig/ERCProductSalesPriceDetailControl'], resolve) },
            { path: 'ERCSystemDataInitializationControl',   component: resolve => require(['./views/erc/baseconfig/ERCSystemDataInitializationControl'], resolve) },
            { path: 'ERCMessageListControl',   component: resolve => require(['./views/erc/baseconfig/ERCMessageListControl'], resolve) },
            { path: 'ERCProjectControlCopy',   component: resolve => require(['./views/erc/baseconfig/ERCProjectControlCopy'], resolve) },
            { path: 'ERCProjectDetailNewControlCopy',   component: resolve => require(['./views/erc/baseconfig/ERCProjectDetailNewControlCopy'], resolve) },
            { path: 'ERCPointTypeControl',   component: resolve => require(['./views/erc/baseconfig/ERCPointTypeControl'], resolve) },
            { path: 'ERCCompanyControl',   component: resolve => require(['./views/erc/baseconfig/ERCCompanyControl'], resolve) }
        ]},


    { path: '/erc/purchasemanage',                   component: resolve => require(['./components/mainSystem'], resolve),
        children: [
          { path: 'ERCPurchaseControl',              component: resolve => require(['./views/erc/purchasemanage/ERCPurchaseControl.vue'], resolve) },
          { path: 'ERCPurchaseDetailControl',        component: resolve => require(['./views/erc/purchasemanage/ERCPurchaseDetailControl'], resolve) },
          { path: 'ERCPurchaseApplyDetailControl',   component: resolve => require(['./views/erc/purchasemanage/ERCPurchaseApplyDetailControl'], resolve) },
          { path: 'ERCPuchasePirntControl',          component: resolve => require(['./views/erc/purchasemanage/ERCPuchasePirntControl'], resolve) },
          { path: 'ERCPurchaseListControl',          component: resolve => require(['./views/erc/purchasemanage/ERCPurchaseListControl.vue'], resolve) },
          { path: 'ERCPuchaseApplyPirntControl',     component: resolve => require(['./views/erc/purchasemanage/ERCPuchaseApplyPirntControl'], resolve) },
          { path: 'ERCQualityAddControl',     component: resolve => require(['./views/erc/purchasemanage/ERCQualityAddControl'], resolve) },
          { path: 'ERCQualityAddDetailControl',     component: resolve => require(['./views/erc/purchasemanage/ERCQualityAddDetailControl'], resolve) },
          { path: 'ERCQualityCheckControl',     component: resolve => require(['./views/erc/purchasemanage/ERCQualityCheckControl'], resolve) },
          { path: 'ERCQualityCheckDetailControl',     component: resolve => require(['./views/erc/purchasemanage/ERCQualityCheckDetailControl'], resolve) },
          { path: 'ERCReturnNoteControl',     component: resolve => require(['./views/erc/purchasemanage/ERCReturnNoteControl'], resolve) },
          { path: 'ERCReturnNoteDetailControl',     component: resolve => require(['./views/erc/purchasemanage/ERCReturnNoteDetailControl'], resolve) }
    ]},

    { path: '/erc/productionmanage',                   component: resolve => require(['./components/mainSystem'], resolve),
        children: [
            { path: 'ERCMasterPlanControl',          component: resolve => require(['./views/erc/productionmanage/ERCMasterPlanControl'], resolve) },
            { path: 'ERCWeeklyPlanControl',          component: resolve => require(['./views/erc/productionmanage/ERCWeeklyPlanControl'], resolve) },
            { path: 'ERCDailyPlanControl',           component: resolve => require(['./views/erc/productionmanage/ERCDailyPlanControl'], resolve) },
            { path: 'ERCProductPlanControl',         component: resolve => require(['./views/erc/productionmanage/ERCProductPlanControl'], resolve) },
            { path: 'ERCProductPlanDetailControl',   component: resolve => require(['./views/erc/productionmanage/ERCProductPlanDetailControl'], resolve) },
            { path: 'ERCProductProcedureControl',    component: resolve => require(['./views/erc/productionmanage/ERCProductProcedureControl'], resolve) },
            { path: 'ERCProductDeviceControl',       component: resolve => require(['./views/erc/productionmanage/ERCProductDeviceControl'], resolve) },
            { path: 'ERCProductPlanVerifyControl',   component: resolve => require(['./views/erc/productionmanage/ERCProductPlanVerifyControl'], resolve) },
            { path: 'ERCPlanVerifyListControl',      component: resolve => require(['./views/erc/productionmanage/ERCPlanVerifyListControl'], resolve) },
            { path: 'ERCPlanVerifyMaterielControl',  component: resolve => require(['./views/erc/productionmanage/ERCPlanVerifyMaterielControl'], resolve) },
            { path: 'ERCProductiveTaskControl',      component: resolve => require(['./views/erc/productionmanage/ERCProductiveTaskControl'], resolve) },
            { path: 'ERCProductiveTaskDetailControl',component: resolve => require(['./views/erc/productionmanage/ERCProductiveTaskDetailControl'], resolve) },
            { path: 'ERCProductTaskControl',      component: resolve => require(['./views/erc/productionmanage/ERCProductTaskControl'], resolve) },
            { path: 'ERCProductTaskDetailControl',      component: resolve => require(['./views/erc/productionmanage/ERCProductTaskDetailControl'], resolve) },
            { path: 'ERCProductPlanExecuteControl',      component: resolve => require(['./views/erc/productionmanage/ERCProductPlanExecuteControl'], resolve) },
        ]},
      { path: '/erc/cashiermanage',                   component: resolve => require(['./components/mainSystem'], resolve),
          children: [
              { path: 'ERCGatheringControl',          component: resolve => require(['./views/erc/cashiermanage/ERCGatheringControl'], resolve) },
              { path: 'ERCGatheringTempControl',          component: resolve => require(['./views/erc/cashiermanage/ERCGatheringTempControl'], resolve) },
              { path: 'ERCPaymentConfirmControl',          component: resolve => require(['./views/erc/cashiermanage/ERCPaymentConfirmControl'], resolve) },
              { path: 'ERCMaterielSRControl',          component: resolve => require(['./views/erc/cashiermanage/ERCMaterielSRControl'], resolve) },
              { path: 'ERCMaterielSRDetailControl',          component: resolve => require(['./views/erc/cashiermanage/ERCMaterielSRDetailControl'], resolve) },
              { path: 'ERCRecordingVoucherControl',          component: resolve => require(['./views/erc/cashiermanage/ERCRecordingVoucherControl'], resolve) },
              { path: 'ERCRecordingVoucherDetailControl',    component: resolve => require(['./views/erc/cashiermanage/ERCRecordingVoucherDetailControl'], resolve) },
              { path: 'ERCSpecialExpenseGatheringSumControl',    component: resolve => require(['./views/erc/cashiermanage/ERCSpecialExpenseGatheringSumControl'], resolve) },
              { path: 'ERCSpecialExpenseGatheringSumDetailControl',    component: resolve => require(['./views/erc/cashiermanage/ERCSpecialExpenseGatheringSumDetailControl'], resolve) },
              { path: 'ERCAccountingListControl',    component: resolve => require(['./views/erc/cashiermanage/ERCAccountingListControl'], resolve) },
              { path: 'ERCRecordingVoucherSCControl',    component: resolve => require(['./views/erc/cashiermanage/ERCRecordingVoucherSCControl'], resolve) },
              { path: 'ERCRecordingVoucherDetailSCControl',    component: resolve => require(['./views/erc/cashiermanage/ERCRecordingVoucherDetailSCControl'], resolve) }
          ]},
    { path: '/erc/inventorymanage',                  component: resolve => require(['./components/mainSystem'], resolve),
      children: [
          { path: 'ERCBuyInControl',                component: resolve => require(['./views/erc/inventorymanage/ERCBuyInControl'], resolve) },
          { path: 'ERCBuyInDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCBuyInDetailControl'], resolve) },
          { path: 'ERCBuyInHistoryControl',         component: resolve => require(['./views/erc/inventorymanage/ERCBuyInHistoryControl'], resolve) },
          { path: 'ERCBuyInHistoryDetailControl',   component: resolve => require(['./views/erc/inventorymanage/ERCBuyInHistoryDetailControl'], resolve) },
          { path: 'ERCBuyInMaterielControl',        component: resolve => require(['./views/erc/inventorymanage/ERCBuyInMaterielControl'], resolve) },
          { path: 'ERCCheckInventoryControl',       component: resolve => require(['./views/erc/inventorymanage/ERCCheckInventoryControl'], resolve) },
          { path: 'ERCCheckInventoryDetailControl', component: resolve => require(['./views/erc/inventorymanage/ERCCheckInventoryDetailControl'], resolve) },
          { path: 'ERCInventoryControl',            component: resolve => require(['./views/erc/inventorymanage/ERCInventoryControl'], resolve) },
          { path: 'ERCInventoryDetailControl',      component: resolve => require(['./views/erc/inventorymanage/ERCInventoryDetailControl'], resolve) },
          { path: 'ERCInventoryZoneDetailControl',  component: resolve => require(['./views/erc/inventorymanage/ERCInventoryZoneDetailControl'], resolve) },
          { path: 'ERCSaleOutControl',              component: resolve => require(['./views/erc/inventorymanage/ERCSaleOutControl'], resolve) },
          { path: 'ERCSaleOutDetailControl',        component: resolve => require(['./views/erc/inventorymanage/ERCSaleOutDetailControl'], resolve) },
          { path: 'ERCSaleOutDetailControlOperate', component: resolve => require(['./views/erc/inventorymanage/ERCSaleOutDetailControlOperate'], resolve) },
          { path: 'ERCSaleOutHistoryControl',       component: resolve => require(['./views/erc/inventorymanage/ERCSaleOutHistoryControl'], resolve) },
          { path: 'ERCSaleOutHistoryDetailControl', component: resolve => require(['./views/erc/inventorymanage/ERCSaleOutHistoryDetailControl'], resolve) },
          { path: 'ERCSaleOutInvoiceControl',       component: resolve => require(['./views/erc/inventorymanage/ERCSaleOutInvoiceControl'], resolve) },
          { path: 'ERCWarehouseControl',            component: resolve => require(['./views/erc/inventorymanage/ERCWarehouseControl'], resolve) },
          { path: 'ERCWarehouseDetailControl',      component: resolve => require(['./views/erc/inventorymanage/ERCWarehouseDetailControl'], resolve) },
          { path: 'ERCInvalidateControl',           component: resolve => require(['./views/erc/inventorymanage/ERCInvalidateControl'], resolve) },
          { path: 'ERCInvalidateApplyControl',           component: resolve => require(['./views/erc/inventorymanage/ERCInvalidateApplyControl'], resolve) },
          { path: 'ERCInvalidateApplyTaskControl',           component: resolve => require(['./views/erc/inventorymanage/ERCInvalidateApplyTaskControl'], resolve) },
          { path: 'ERCBuyInMovingMaterielControl',        component: resolve => require(['./views/erc/inventorymanage/ERCBuyInMovingMaterielControl'], resolve) },
          { path: 'ERCStockInApplyControl',        component: resolve => require(['./views/erc/inventorymanage/ERCStockInApplyControl'], resolve) },
          { path: 'ERCStockInApplyDetailControl',        component: resolve => require(['./views/erc/inventorymanage/ERCStockInApplyDetailControl'], resolve) },
          { path: 'ERCStockOutApplyControl',        component: resolve => require(['./views/erc/inventorymanage/ERCStockOutApplyControl'], resolve) },
          { path: 'ERCStockOutApplyDetailControl',        component: resolve => require(['./views/erc/inventorymanage/ERCStockOutApplyDetailControl'], resolve) },
          { path: 'ERCOtherInDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCOtherInDetailControl'], resolve) },
          { path: 'ERCOtherOutDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCOtherOutDetailControl'], resolve) },
          { path: 'ERCOtherInMaterielControl',          component: resolve => require(['./views/erc/inventorymanage/ERCOtherInMaterielControl'], resolve) },
          { path: 'ERCOtherInHistoryDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCOtherInHistoryDetailControl'], resolve) },
          { path: 'ERCProductInHistoryDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCProductInHistoryDetailControl'], resolve) },
          { path: 'ERCOtherOutDetailControlApply',          component: resolve => require(['./views/erc/inventorymanage/ERCOtherOutDetailControlApply'], resolve) },
          { path: 'ERCIdleApplyControl',              component: resolve => require(['./views/erc/inventorymanage/ERCIdleApplyControl'], resolve) },
          { path: 'ERCIdleApplyDetailControl',        component: resolve => require(['./views/erc/inventorymanage/ERCIdleApplyDetailControl'], resolve) },
          { path: 'ERCOtherOutHistoryDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCOtherOutHistoryDetailControl.vue'], resolve) },
          { path: 'ERCProductOutHistoryDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCProductOutHistoryDetailControl.vue'], resolve) },
          { path: 'ERCCollectGoodsControl',          component: resolve => require(['./views/erc/inventorymanage/ERCCollectGoodsControl.vue'], resolve) },
          { path: 'ERCCollectGoodsDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCCollectGoodsDetailControl.vue'], resolve) },
          { path: 'ERCReceiptListControl',          component: resolve => require(['./views/erc/inventorymanage/ERCReceiptListControl.vue'], resolve) },
          { path: 'ERCReceiptDetailControl',          component: resolve => require(['./views/erc/inventorymanage/ERCReceiptDetailControl.vue'], resolve) },
          { path: 'ERCProductInItemsControl',          component: resolve => require(['./views/erc/inventorymanage/ERCProductInItemsControl.vue'], resolve) },
          { path: 'ERCProductInSubmitControl',          component: resolve => require(['./views/erc/inventorymanage/ERCProductInSubmitControl.vue'], resolve) },
          { path: 'ERCProductOutItemsControl',          component: resolve => require(['./views/erc/inventorymanage/ERCProductOutItemsControl.vue'], resolve) },
          { path: 'ERCProductOutSubmitControl',          component: resolve => require(['./views/erc/inventorymanage/ERCProductOutSubmitControl.vue'], resolve) }
      ]},
    { path: '/erc/homepage',                        component: resolve => require(['./components/mainSystem'], resolve),
      children: [
        { path: 'ERCHomePageControl',               component: resolve => require(['./views/erc/homepage/ERCHomePageControl.vue'], resolve) },
    ]},
    { path: '/erc/longtermassets',                   component: resolve => require(['./components/mainSystem'], resolve),
      children: [
          { path: 'ERCFixedAssetsControl',              component: resolve => require(['./views/erc/longtermassets/ERCFixedAssetsControl'], resolve) },
          { path: 'ERCFixedAssetsRepairMaterials',              component: resolve => require(['./views/erc/longtermassets/ERCFixedAssetsRepairMaterials'], resolve) },
          { path: 'ERCAssetPurchaseDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetPurchaseDetailControl'], resolve) },
          { path: 'ERCAssetsAcceptanceDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetsAcceptanceDetailControl'], resolve) },
          { path: 'ERCAssetPurchaseTaskDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetPurchaseTaskDetailControl'], resolve) },
          { path: 'ERCAssetsAcceptanceTaskDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetsAcceptanceTaskDetailControl'], resolve) },
          { path: 'ERCConsumablesControl',           component: resolve => require(['./views/erc/longtermassets/ERCConsumablesControl'], resolve) },
          { path: 'ERCConsumablesDetailControl',           component: resolve => require(['./views/erc/longtermassets/ERCConsumablesDetailControl'], resolve) },
          { path: 'ERCAmortizeControl',   component: resolve => require(['./views/erc/longtermassets/ERCAmortizeControl'], resolve) },
          { path: 'ERCAmortizeDataControl',   component: resolve => require(['./views/erc/longtermassets/ERCAmortizeDataControl'], resolve) },
          { path: 'ERCAmortizeDetailControl',   component: resolve => require(['./views/erc/longtermassets/ERCAmortizeDetailControl'], resolve) },
          { path: 'ERCAmortizeReceiveControl',   component: resolve => require(['./views/erc/longtermassets/ERCAmortizeReceiveControl'], resolve) },
          { path: 'ERCAmortizeReceiveDetailControl',   component: resolve => require(['./views/erc/longtermassets/ERCAmortizeReceiveDetailControl'], resolve) },
          { path: 'ERCAmortizeConsumeControl',   component: resolve => require(['./views/erc/longtermassets/ERCAmortizeConsumeControl'], resolve) },
          { path: 'ERCAmortizeConsumeDetailControl',   component: resolve => require(['./views/erc/longtermassets/ERCAmortizeConsumeDetailControl'], resolve) },
          { path: 'ERCAssetRetirementControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetRetirementControl'], resolve) },
          { path: 'ERCFixedAssetsScrapDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCFixedAssetsScrapDetailControl'], resolve) },
          { path: 'ERCDeferredAssetsScrapDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCDeferredAssetsScrapDetailControl'], resolve) },
          { path: 'ERCValueConsumablesScrapDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCValueConsumablesScrapDetailControl'], resolve) },
          { path: 'ERCFixedAssetsScrapTaskDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCFixedAssetsScrapTaskDetailControl'], resolve) },
          { path: 'ERCAssetInventoryControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetInventoryControl'], resolve) },
          { path: 'ERCAssetInventoryDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetInventoryDetailControl'], resolve) },
          { path: 'ERCAssetInventoryUsersDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetInventoryUsersDetailControl'], resolve) },
          { path: 'ERCAssetInventoryTaskDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetInventoryTaskDetailControl'], resolve) },
          { path: 'ERCAssetInventoryUsersTaskDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetInventoryUsersTaskDetailControl'], resolve) },
          { path: 'ERCAmortizeControlCopy',              component: resolve => require(['./views/erc/longtermassets/ERCAmortizeControlCopy'], resolve) },
          { path: 'ERCAmortizeDetailControlCopy',              component: resolve => require(['./views/erc/longtermassets/ERCAmortizeDetailControlCopy'], resolve) },
          { path: 'ERCAmortizeScribeOrderControl',              component: resolve => require(['./views/erc/longtermassets/ERCAmortizeScribeOrderControl'], resolve) },
          { path: 'ERCAmortizeScribeOrderDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAmortizeScribeOrderDetailControl'], resolve) },
          { path: 'ERCAmortizePurchaseOrderControl',              component: resolve => require(['./views/erc/longtermassets/ERCAmortizePurchaseOrderControl'], resolve) },
          { path: 'ERCAmortizePurchaseOrderDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAmortizePurchaseOrderDetailControl'], resolve) },
          { path: 'ERCAssetRetirementDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCAssetRetirementDetailControl'], resolve) },
          { path: 'ERCDevelopControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopControl'], resolve) },
          { path: 'ERCDevelopControlCopy',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopControlCopy'], resolve) },
          { path: 'ERCDevelopDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopDetailControl'], resolve) },
          { path: 'ERCDevelopDetailControlCopy',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopDetailControlCopy'], resolve) },
          { path: 'ERCAmortizeScribeOrderDetailControlCopy',              component: resolve => require(['./views/erc/longtermassets/ERCAmortizeScribeOrderDetailControlCopy'], resolve) },
          { path: 'ERCDevelopScribeOrderDetailControlCopy',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopScribeOrderDetailControlCopy'], resolve) },
          { path: 'ERCDevelopScribeOrderControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopScribeOrderControl'], resolve) },
          { path: 'ERCDevelopScribeOrderDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopScribeOrderDetailControl'], resolve) },
          { path: 'ERCDevelopReceiveControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopReceiveControl'], resolve) },
          { path: 'ERCDevelopReceiveDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopReceiveDetailControl'], resolve) },
          { path: 'ERCDevelopPurchaseOrderControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopPurchaseOrderControl'], resolve) },
          { path: 'ERCDevelopPurchaseOrderDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopPurchaseOrderDetailControl'], resolve) },
          { path: 'ERCDevelopConsumeControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopConsumeControl'], resolve) },
          { path: 'ERCDevelopConsumeDetailControl',              component: resolve => require(['./views/erc/longtermassets/ERCDevelopConsumeDetailControl'], resolve) },
          // { path: 'ERCAmortizeConsumeControlCopy',              component: resolve => require(['./views/erc/longtermassets/ERCAmortizeConsumeControlCopy'], resolve) },
      ]},

      { path: '/shxp/baseconfig',                        component: resolve => require(['./components/mainSystem'], resolve),
          children: [
              { path: 'SHXPProductControl',               component: resolve => require(['./views/shxp/baseconfig/SHXPProductControl.vue'], resolve) },
              { path: 'SHXPSeatClassControl',               component: resolve => require(['./views/shxp/baseconfig/SHXPSeatClassControl.vue'], resolve) },
          ]},
    { path: '/system',          component: resolve => require(['./components/mainSystem'], resolve),
      children: [
        { path: 'home',                   component: resolve => require(['./views/home'], resolve) },
    ]},
    { path: '/example',           component: resolve => require(['./components/mainSystem'], resolve),
      children: [
        { path: 'example',   component: resolve => require(['./views/example/example'], resolve) },
    ]}
  ]
})
